baseURL = 'https://cczywyc.love'
languageCode = 'zh-cn'
defaultContentLanguage = "zh-cn"
title = 'cczywyc blog'
theme = 'puppet'

paginate = 5

hasCJKLanguage = true
enableInlineShortcodes = true
enableEmoji = true
ignoreErrors = ["error-remote-getjson"]

disqusShortname = ""
googleAnalytics = ""

[outputs]
home = ["HTML", "JSON", "RSS"]

[markup]
[markup.highlight]
noClasses = true
codeFences = true
guessSyntax = true
lineNos = true
lineNumbersInTable = false
style = "dracula"

[markup.goldmark.renderer]
unsafe = true

[menu]
[[menu.main]]
identifier = "home"
name = "首页"
url = "/"
weight = -100
[[menu.main]]
identifier = "archive"
name = "归档"
url = "/archive/"
weight = 10
[[menu.main]]
identifier = "about"
name = "关于"
url = "/about/"
weight = 50
[[menu.main]]
identifier = "github"
name = "Github"
url = "https://github.com/cczywyc"
weight = 100

[params]
author = "cczywyc"
description = "一个爱折腾的人"
keywords = "blog,developer,personal"
img_home = "img/home-bg.jpg"
img_404 = "img/404-bg.jpg"

[params.sidebar]
enable = true
gravatarEmail = ""
avatar = "img/home-bg.jpg"
bio = "cczywyc personal website"

[params.social]
twitter = "cczywyc"
zhihu = "cczywyc"
weibo = "6026902801"
github = "cczywyc"
email = 'cczywyc@qq.com'
rss = true

[params.giscus]
enable = true
repo = "cczywyc/blog"
repo_id = "R_kgDOJT0jQQ"
category = "Announcements"
category_id = "DIC_kwDOJT0jQc4CV9qk"
input_position = "top"
reactions_enabled = "1"
emit_metadata = "0"
mapping = "pathname"
theme = "light"
lang = "zh-CN"
